options(scipen = 99)

distribution10x10 = read.csv(file.path(getwd(), "UnitTests\\bin\\x64\\Release\\FE640_set3_20_rt_objectiveDistribution100.csv"), fileEncoding = "UTF-8-BOM", header = FALSE)
distribution50x40 = read.csv(file.path(getwd(), "UnitTests\\bin\\x64\\Release\\FE640_set3_20_rt_2kobjectiveDistribution.csv"), fileEncoding = "UTF-8-BOM", header = FALSE)
distribution25x80 = read.csv(file.path(getwd(), "UnitTests\\bin\\x64\\Release\\FE640_set3_20_rt_2k25objectiveDistribution.csv"), fileEncoding = "UTF-8-BOM", header = FALSE)
distribution10x200 = read.csv(file.path(getwd(), "UnitTests\\bin\\x64\\Release\\FE640_set3_20_rt_2k10objectiveDistribution.csv"), fileEncoding = "UTF-8-BOM", header = FALSE)

c(max(distribution10x10$V1), max(distribution50x40$V1), max(distribution25x80$V1), max(distribution10x200$V1)) / 1E6

breaks100 = seq(0, 0.25, length.out = 100)
breaks2k = seq(0, 10, length.out = 100)
png("objectiveDistribution.png", width = 6.5, height = 5, units = "in", res = 300)
par(mar = c(3, 3, 1, 1), mgp = c(2, 0.6, 0), mfrow = c(2, 2))
hist(distribution10x10$V1 / 1E6, breaks = breaks100, main = "", xlab = "", xlim = c(0, 0.25), ylab = "10x10 runs", ylim = c(0, 80))
hist(distribution50x40$V1 / 1E6, breaks = breaks2k, main = "", xlab = "", xlim = c(0, 10), ylab = "50x40 runs", ylim = c(0, 80))
hist(distribution25x80$V1 / 1E6, breaks = breaks2k, main = "", xlab = expression("objective, Mu"^2), xlim = c(0, 10), ylab = "25x80 runs", ylim = c(0, 80))
hist(distribution10x200$V1 / 1E6, breaks = breaks2k, main = "", xlab = expression("objective, Mu"^2), xlim = c(0, 10), ylab = "10x200 runs", ylim = c(0, 80))
dev.off()

objectives10x10 = read.csv(file.path(getwd(), "UnitTests\\bin\\x64\\Release\\FE640_set3_20_rt_objective100.csv"), fileEncoding = "UTF-8-BOM")
objectives50x40 = read.csv(file.path(getwd(), "UnitTests\\bin\\x64\\Release\\FE640_set3_20_rt_2kobjective.csv"), fileEncoding = "UTF-8-BOM")
objectives25x80 = read.csv(file.path(getwd(), "UnitTests\\bin\\x64\\Release\\FE640_set3_20_rt_2k25objective.csv"), fileEncoding = "UTF-8-BOM")
objectives10x200 = read.csv(file.path(getwd(), "UnitTests\\bin\\x64\\Release\\FE640_set3_20_rt_2k10objective.csv"), fileEncoding = "UTF-8-BOM")

objectives = rbind(c(max(objectives10x10$SA0), max(objectives50x40$SA0), max(objectives25x80$SA0), max(objectives10x200$SA0)),
                   c(min(objectives10x10$SA0), min(objectives50x40$SA0), min(objectives25x80$SA0), min(objectives10x200$SA0)))
log10(objectives / 1E6)

png("objectives.png", width = 6.5, height = 4, units = "in", res = 300)
par(mar = c(3, 3, 1, 1), mgp = c(1.7, 0.7, 0), mfrow = c(2, 4))
plot(1E-3 * objectives10x10$iteration, 1E-6 * objectives10x10$SA0, log = "y", type = "l", xaxt = "n", xlab = "", xlim = c(0, 800), yaxt = "n", ylab = expression("objective, Mu"^2), ylim = 10^c(-1, 0), panel.first = grid())
axis(side = 1, at = axTicks(1), labels = formatC(axTicks(1), format = "d", big.mark = ','))
axis(side = 2, at = axTicks(2), labels = formatC(axTicks(2), format = "f", drop0trailing = TRUE))
plot(1E-6 * objectives50x40$iteration, 1E-6 * objectives50x40$SA0, log = "y", type = "l", xaxt = "n", xlab = "", xlim = c(0, 8), yaxt = "n", ylab = "", ylim = 10^c(0, 5.5), panel.first = grid())
axis(side = 1, at = axTicks(1), labels = formatC(axTicks(1), format = "d", big.mark = ','))
axis(side = 2, at = axTicks(2), labels = formatC(axTicks(2), format = "f", drop0trailing = TRUE))
plot(1E-6 * objectives25x80$iteration, 1E-6 * objectives25x80$SA0, log = "y", type = "l", xaxt = "n", xlab = "", xlim = c(0, 8), yaxt = "n", ylab = "", ylim = 10^c(0, 5.5), panel.first = grid())
axis(side = 1, at = axTicks(1), labels = formatC(axTicks(1), format = "d", big.mark = ','))
axis(side = 2, at = axTicks(2), labels = formatC(axTicks(2), format = "f", drop0trailing = TRUE))
plot(1E-6 * objectives10x200$iteration, 1E-6 * objectives10x200$SA0, log = "y", type = "l", xaxt = "n", xlab = "", xlim = c(0, 8), yaxt = "n", ylab = "", ylim = 10^c(0, 5.5), panel.first = grid())
axis(side = 1, at = axTicks(1), labels = formatC(axTicks(1), format = "d", big.mark = ','))
axis(side = 2, at = axTicks(2), labels = formatC(axTicks(2), format = "f", drop0trailing = TRUE))

plot(1E-3 * objectives10x10$iteration, 1E-6 * objectives10x10$SA0, log = "y", type = "l", xaxt = "n", xlab = "10x10 iteration, k", xlim = c(0, 800), yaxt = "n", ylab = expression("objective, Mu"^2), ylim = c(0.2, 0.3), panel.first = grid())
axis(side = 1, at = axTicks(1), labels = formatC(axTicks(1), format = "d", big.mark = ','))
axis(side = 2, at = axTicks(2), labels = formatC(axTicks(2), format = "f", drop0trailing = TRUE))
plot(1E-6 * objectives50x40$iteration, 1E-6 * objectives50x40$SA0, log = "y", type = "l", xaxt = "n", xlab = "50x40 iteration, M", xlim = c(0, 8), yaxt = "n", ylab = "", ylim = 10^c(0.5, 1), panel.first = grid())
axis(side = 1, at = axTicks(1), labels = formatC(axTicks(1), format = "d", big.mark = ','))
axis(side = 2, at = axTicks(2), labels = formatC(axTicks(2), format = "f", drop0trailing = TRUE))
plot(1E-6 * objectives25x80$iteration, 1E-6 * objectives25x80$SA0, log = "y", type = "l", xaxt = "n", xlab = "25x80 iteration, M", xlim = c(0, 8), yaxt = "n", ylab = "", ylim = 10^c(0.5, 1), panel.first = grid())
axis(side = 1, at = axTicks(1), labels = formatC(axTicks(1), format = "d", big.mark = ','))
axis(side = 2, at = axTicks(2), labels = formatC(axTicks(2), format = "f", drop0trailing = TRUE))
plot(1E-6 * objectives10x200$iteration, 1E-6 * objectives10x200$SA0, log = "y", type = "l", xaxt = "n", xlab = "10x200 iteration, M", xlim = c(0, 8), yaxt = "n", ylab = "", ylim = 10^c(0.5, 1), panel.first = grid())
axis(side = 1, at = axTicks(1), labels = formatC(axTicks(1), format = "d", big.mark = ','))
axis(side = 2, at = axTicks(2), labels = formatC(axTicks(2), format = "f", drop0trailing = TRUE))
dev.off()
